"""Scoring-based insurance company detection."""

INSURANCE_COMPANIES = {
    "ACKO": "ACKO GENERAL INSURANCE LIMITED",
    "TATA AIG": "TATA AIG GENERAL INSURANCE COMPANY LIMITED",
    "ICICI LOMBARD": "ICICI LOMBARD GENERAL INSURANCE COMPANY LIMITED",
    "RELIANCE": "RELIANCE GENERAL INSURANCE COMPANY LIMITED",
    "DIGIT": "GO DIGIT GENERAL INSURANCE LIMITED",
    "GO DIGIT": "GO DIGIT GENERAL INSURANCE LIMITED",
    "IFFCO": "IFFCO TOKIO GENERAL INSURANCE COMPANY LIMITED",
    "IFFCO TOKIO": "IFFCO TOKIO GENERAL INSURANCE COMPANY LIMITED",
    "SHRIRAM": "SHRIRAM GENERAL INSURANCE COMPANY LIMITED",
    "HDFC ERGO": "HDFC ERGO GENERAL INSURANCE COMPANY LIMITED",
    "SBI GENERAL": "SBI GENERAL INSURANCE COMPANY LIMITED",
    "BAJAJ ALLIANZ": "BAJAJ ALLIANZ GENERAL INSURANCE COMPANY LIMITED",
    "ROYAL SUNDARAM": "ROYAL SUNDARAM GENERAL INSURANCE COMPANY LIMITED",
    "LIBERTY": "LIBERTY GENERAL INSURANCE COMPANY LIMITED",
    "MAGMA": "MAGMA HDI GENERAL INSURANCE COMPANY LIMITED",
    "MAGMA HDI": "MAGMA HDI GENERAL INSURANCE COMPANY LIMITED",
    "CHOLA": "CHOLAMANDALAM MS GENERAL INSURANCE COMPANY LIMITED",
    "CHOLAMANDALAM": "CHOLAMANDALAM MS GENERAL INSURANCE COMPANY LIMITED",
    "FUTURE GENERALI": "FUTURE GENERALI INDIA INSURANCE COMPANY LIMITED",
    "UNIVERSAL SOMPO": "UNIVERSAL SOMPO GENERAL INSURANCE COMPANY LIMITED",
    "NAVI": "NAVI GENERAL INSURANCE LIMITED",
    "KOTAK": "KOTAK MAHINDRA GENERAL INSURANCE COMPANY LIMITED",
    "ZUNO": "ZUNO GENERAL INSURANCE LIMITED",
    "EDELWEISS": "EDELWEISS GENERAL INSURANCE COMPANY LIMITED",
    "RAHEJA QBE": "RAHEJA QBE GENERAL INSURANCE COMPANY LIMITED",
    "STAR HEALTH": "STAR HEALTH AND ALLIED INSURANCE COMPANY LIMITED",
    "NIVA BUPA": "NIVA BUPA HEALTH INSURANCE COMPANY LIMITED",
    "CARE HEALTH": "CARE HEALTH INSURANCE LIMITED",
    "CARE INSURANCE": "CARE HEALTH INSURANCE LIMITED",
    "MANIPALCIGNA": "MANIPALCIGNA HEALTH INSURANCE COMPANY LIMITED",
    "ADITYA BIRLA": "ADITYA BIRLA HEALTH INSURANCE COMPANY LIMITED",
    "RELIGARE": "CARE HEALTH INSURANCE LIMITED",
    "LIC": "LIFE INSURANCE CORPORATION OF INDIA",
    "TATA AIA": "TATA AIA LIFE INSURANCE COMPANY LIMITED",
    "HDFC LIFE": "HDFC LIFE INSURANCE COMPANY LIMITED",
    "ICICI PRUDENTIAL": "ICICI PRUDENTIAL LIFE INSURANCE COMPANY LIMITED",
    "MAX LIFE": "MAX LIFE INSURANCE COMPANY LIMITED",
    "SBI LIFE": "SBI LIFE INSURANCE COMPANY LIMITED",
    "BAJAJ ALLIANZ LIFE": "BAJAJ ALLIANZ LIFE INSURANCE COMPANY LIMITED",
    "KOTAK LIFE": "KOTAK MAHINDRA LIFE INSURANCE COMPANY LIMITED",
    "PNB METLIFE": "PNB METLIFE INDIA INSURANCE COMPANY LIMITED",
    "CANARA HSBC": "CANARA HSBC LIFE INSURANCE COMPANY LIMITED",
    "BHARTI AXA LIFE": "BHARTI AXA LIFE INSURANCE COMPANY LIMITED",
    "INDIAFIRST": "INDIAFIRST LIFE INSURANCE COMPANY LIMITED"
}


def detect_company(raw_text: str) -> str:
    if not raw_text:
        return "Unknown"

    text = raw_text.upper()
    scores = {}

    for keyword, company in INSURANCE_COMPANIES.items():
        score = text.count(keyword.upper())
        if score:
            scores[company] = scores.get(company, 0) + score

    if not scores:
        return "Unknown"

    best_company, best_score = max(scores.items(), key=lambda item: (item[1], item[0]))
    return best_company if best_score > 0 else "Unknown"